In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [2]:
df= pd.read_csv('genres.csv')

In [3]:
genres_clean = df.copy()

In [4]:
print("Shape:", genres_clean.shape)

print("\nMissing values:")
print(genres_clean.isnull().sum())

print("\nExact duplicates:")
print(genres_clean.duplicated().sum())

print("\nDuplicate genre_id:")
print(genres_clean['genre_id'].duplicated().sum())

print("\nDuplicate genre_name:")
print(genres_clean['genre_name'].duplicated().sum())

print("\nInvalid genre_id:")
print((genres_clean['genre_id'] <= 0).sum())

Shape: (19, 2)

Missing values:
genre_id      0
genre_name    0
dtype: int64

Exact duplicates:
0

Duplicate genre_id:
0

Duplicate genre_name:
0

Invalid genre_id:
0

In [5]:
genres_clean[
    genres_clean['genre_name'].str.strip() == ''
]

Empty DataFrame
Columns: [genre_id, genre_name]
Index: []

In [6]:
genres_clean.to_csv('genres_clean.csv', index=False)

In [7]:
df= pd.read_csv('movies.csv')

In [8]:
df.columns

Index(['movie_id', 'title', 'original_language', 'release_date', 'runtime',
       'budget', 'revenue', 'popularity', 'vote_average', 'vote_count',
       'status', 'overview'],
      dtype='str')

In [9]:
df.shape

(2509, 12)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   movie_id           2509 non-null   int64
 1   title              2509 non-null   str
 2   original_language  2509 non-null   str
 3   release_date       2509 non-null   str
 4   runtime            2509 non-null   int64
 5   budget             2509 non-null   float64
 6   revenue            2509 non-null   float64
 7   popularity         2509 non-null   float64
 8   vote_average       2509 non-null   float64
 9   vote_count         2509 non-null   int64
 10  status             2509 non-null   str
 11  overview           2509 non-null   str
dtypes: float64(4), int64(3), str(5)
memory usage: 989.6 KB

In [11]:
movies_clean = df.copy()

In [12]:
movies_clean.isnull().sum()

movie_id             0
title                0
original_language    0
release_date         0
runtime              0
budget               0
revenue              0
popularity           0
vote_average         0
vote_count           0
status               0
overview             0
dtype: int64

In [13]:
movies_clean.duplicated().sum()

np.int64(6)

In [14]:
movies_clean = movies_clean.drop_duplicates()

In [15]:
movies_clean = movies_clean.reset_index(drop=True)

In [16]:
movies_clean['movie_id'].duplicated().sum()

np.int64(0)

In [17]:
movies_clean[movies_clean['movie_id'] <= 0]

Empty DataFrame
Columns: [movie_id, title, original_language, release_date, runtime, budget, revenue, popularity, vote_average, vote_count, status, overview]
Index: []

In [18]:
movies_clean[movies_clean['title'].str.strip() == '']

Empty DataFrame
Columns: [movie_id, title, original_language, release_date, runtime, budget, revenue, popularity, vote_average, vote_count, status, overview]
Index: []

In [19]:
movies_clean[movies_clean['original_language'].str.strip() == '']

Empty DataFrame
Columns: [movie_id, title, original_language, release_date, runtime, budget, revenue, popularity, vote_average, vote_count, status, overview]
Index: []

In [20]:
movies_clean[movies_clean['status'].str.strip() == '']

Empty DataFrame
Columns: [movie_id, title, original_language, release_date, runtime, budget, revenue, popularity, vote_average, vote_count, status, overview]
Index: []

In [21]:
movies_clean[movies_clean['overview'].str.strip() == '']

Empty DataFrame
Columns: [movie_id, title, original_language, release_date, runtime, budget, revenue, popularity, vote_average, vote_count, status, overview]
Index: []

In [22]:
movies_clean['release_date'] = pd.to_datetime(
    movies_clean['release_date'],
    errors='coerce'
)

In [23]:
movies_clean['release_date'].isnull().sum()

np.int64(0)

In [24]:
df[
    pd.to_datetime(
        df['release_date'],
        errors='coerce'
    ).isnull()
]['release_date']

Series([], Name: release_date, dtype: str)

In [25]:
movies_clean['runtime'].describe()

count    2503.000000
mean      114.413903
std        21.418867
min        45.000000
25%        99.000000
50%       111.000000
75%       126.000000
max       242.000000
Name: runtime, dtype: float64

In [26]:
movies_clean[movies_clean['runtime'] <= 0]

Empty DataFrame
Columns: [movie_id, title, original_language, release_date, runtime, budget, revenue, popularity, vote_average, vote_count, status, overview]
Index: []

In [27]:
movies_clean[movies_clean['budget'] < 0]

Empty DataFrame
Columns: [movie_id, title, original_language, release_date, runtime, budget, revenue, popularity, vote_average, vote_count, status, overview]
Index: []

In [28]:
movies_clean[movies_clean['revenue'] < 0]

Empty DataFrame
Columns: [movie_id, title, original_language, release_date, runtime, budget, revenue, popularity, vote_average, vote_count, status, overview]
Index: []

In [29]:
movies_clean[movies_clean['popularity'] < 0]

Empty DataFrame
Columns: [movie_id, title, original_language, release_date, runtime, budget, revenue, popularity, vote_average, vote_count, status, overview]
Index: []

In [30]:
movies_clean[
    (movies_clean['vote_average'] < 0) |
    (movies_clean['vote_average'] > 10)
]

Empty DataFrame
Columns: [movie_id, title, original_language, release_date, runtime, budget, revenue, popularity, vote_average, vote_count, status, overview]
Index: []

In [31]:
movies_clean[movies_clean['vote_count'] < 0]

Empty DataFrame
Columns: [movie_id, title, original_language, release_date, runtime, budget, revenue, popularity, vote_average, vote_count, status, overview]
Index: []

In [32]:
movies_clean['status'].value_counts(dropna=False)

status
Released    2503
Name: count, dtype: int64

In [33]:
movies_clean['original_language'].value_counts().head(30)

original_language
en    2363
ja      34
fr      25
it      19
es      15
de      11
ko       9
cn       6
sv       4
pt       2
da       2
hi       2
id       2
zh       2
pl       1
tr       1
lv       1
fi       1
el       1
ru       1
sr       1
Name: count, dtype: int64

In [34]:
movies_clean['overview'].str.len().describe()

count    2503.000000
mean      271.810627
std       121.628982
min        58.000000
25%       173.000000
50%       249.000000
75%       350.500000
max       812.000000
Name: overview, dtype: float64

In [35]:
movies_clean[
    movies_clean['overview'].str.strip() == ''
]

Empty DataFrame
Columns: [movie_id, title, original_language, release_date, runtime, budget, revenue, popularity, vote_average, vote_count, status, overview]
Index: []

In [36]:
movies_clean.dtypes

movie_id                      int64
title                           str
original_language               str
release_date         datetime64[us]
runtime                       int64
budget                      float64
revenue                     float64
popularity                  float64
vote_average                float64
vote_count                    int64
status                          str
overview                        str
dtype: object

In [37]:
print("Shape:", movies_clean.shape)

print("\nMissing values:")
print(movies_clean.isnull().sum())

print("\nExact duplicates:")
print(movies_clean.duplicated().sum())

print("\nDuplicate movie_id:")
print(movies_clean['movie_id'].duplicated().sum())

print("\nInvalid movie_id:")
print((movies_clean['movie_id'] <= 0).sum())

print("\nNegative runtime:")
print((movies_clean['runtime'] < 0).sum())

print("\nNegative budget:")
print((movies_clean['budget'] < 0).sum())

print("\nNegative revenue:")
print((movies_clean['revenue'] < 0).sum())

print("\nNegative popularity:")
print((movies_clean['popularity'] < 0).sum())

print("\nInvalid vote_average:")
print(
    (
        (movies_clean['vote_average'] < 0) |
        (movies_clean['vote_average'] > 10)
    ).sum()
)

print("\nNegative vote_count:")
print((movies_clean['vote_count'] < 0).sum())

Shape: (2503, 12)

Missing values:
movie_id             0
title                0
original_language    0
release_date         0
runtime              0
budget               0
revenue              0
popularity           0
vote_average         0
vote_count           0
status               0
overview             0
dtype: int64

Exact duplicates:
0

Duplicate movie_id:
0

Invalid movie_id:
0

Negative runtime:
0

Negative budget:
0

Negative revenue:
0

Negative popularity:
0

Invalid vote_average:
0

Negative vote_count:
0

In [38]:
movies_clean.to_csv('movies_clean.csv', index=False)

In [39]:
df= pd.read_csv('movie_genres.csv')

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6888 entries, 0 to 6887
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  6888 non-null   int64
 1   genre_id  6888 non-null   int64
dtypes: int64(2)
memory usage: 107.8 KB

In [41]:
movies_genres_clean = df.copy()

In [42]:
movies_genres_clean.isna().sum()

movie_id    0
genre_id    0
dtype: int64

In [43]:
movies_genres_clean.duplicated(
    subset=['movie_id', 'genre_id']
).sum()

np.int64(10)

In [44]:
movies_genres_clean[
    movies_genres_clean.duplicated(
        subset=['movie_id', 'genre_id'],
        keep=False
    )
].sort_values(['movie_id', 'genre_id'])

      movie_id  genre_id
3257        90        28
6881        90        28
5937      1429        80
6885      1429        80
5787      8914        28
6884      8914        28
4607      9334        14
6882      9334        14
5345      9477        12
6879      9477        12
5269      9705        53
6883      9705        53
1498     57800     10751
6886     57800     10751
2906    411088        18
6880    411088        18
5728    429300        53
6878    429300        53
4184    456740        27
6887    456740        27

In [45]:
orphan_movies = movies_genres_clean[
    ~movies_genres_clean['movie_id'].isin(
        movies_clean['movie_id']
    )
]

orphan_movies

Empty DataFrame
Columns: [movie_id, genre_id]
Index: []

In [46]:
print("Orphan movie relationships:", len(orphan_movies))

Orphan movie relationships: 0

In [47]:
print(
    "Invalid movie_id:",
    (movies_genres_clean['movie_id'] <= 0).sum()
)

print(
    "Invalid genre_id:",
    (movies_genres_clean['genre_id'] <= 0).sum()
)

Invalid movie_id: 0
Invalid genre_id: 0

In [48]:
print("Exact duplicates:",
      movies_genres_clean.duplicated().sum())

print("Duplicate movie-genre relationships:",
      movies_genres_clean.duplicated(
          subset=['movie_id', 'genre_id']
      ).sum())

print("Orphan movies:",
      len(orphan_movies))

print("Orphan genres:",
      len(orphan_movies))

print("Invalid movie IDs:",
      (movies_genres_clean['movie_id'] <= 0).sum())

print("Invalid genre IDs:",
      (movies_genres_clean['genre_id'] <= 0).sum())

Exact duplicates: 10
Duplicate movie-genre relationships: 10
Orphan movies: 0
Orphan genres: 0
Invalid movie IDs: 0
Invalid genre IDs: 0

In [49]:
movies_genres_clean = movies_genres_clean.drop_duplicates(
    subset=['movie_id', 'genre_id']
)

In [50]:
movies_genres_clean = movies_genres_clean.reset_index(drop=True)

In [51]:
print("Shape:", movies_genres_clean.shape)

print("\nMissing values:")
print(movies_genres_clean.isnull().sum())

print("\nExact duplicates:")
print(movies_genres_clean.duplicated().sum())

print("\nDuplicate movie-genre relationships:")
print(
    movies_genres_clean.duplicated(
        subset=['movie_id', 'genre_id']
    ).sum()
)

print("\nOrphan movies:")
print(
    (~movies_genres_clean['movie_id'].isin(
        movies_clean['movie_id']
    )).sum()
)

print("\nOrphan genres:")
print(
    (~movies_genres_clean['genre_id'].isin(
        genres_clean['genre_id']
    )).sum()
)

print("\nInvalid movie IDs:")
print((movies_genres_clean['movie_id'] <= 0).sum())

print("\nInvalid genre IDs:")
print((movies_genres_clean['genre_id'] <= 0).sum())

Shape: (6878, 2)

Missing values:
movie_id    0
genre_id    0
dtype: int64

Exact duplicates:
0

Duplicate movie-genre relationships:
0

Orphan movies:
0

Orphan genres:
0

Invalid movie IDs:
0

Invalid genre IDs:
0

In [52]:
movies_genres_clean.to_csv(
    'movies_genres_clean.csv',
    index=False
)

In [53]:
df = pd.read_csv('movie_keywords.csv')

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41701 entries, 0 to 41700
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      41701 non-null  int64
 1   keyword_id    41701 non-null  int64
 2   keyword_name  41701 non-null  str
dtypes: int64(2), str(1)
memory usage: 1.4 MB

In [55]:
movies_keyword_clean = df.copy()

In [56]:
movies_keyword_clean.duplicated().sum()

np.int64(20)

In [57]:
movies_keyword_clean[
    movies_keyword_clean.duplicated(keep=False)
].sort_values(['movie_id', 'keyword_id'])

       movie_id  keyword_id            keyword_name
4285        111         701                    cuba
41698       111         701                    cuba
28217       947      210434              thoughtful
41690       947      210434              thoughtful
14844       948        2546                    mask
41692       948        2546                    mask
3211       1271      329753             epic heroes
41696      1271      329753             epic heroes
12570      1368        6149                  police
41684      1368        6149                  police
31271      1381        3755              transience
41681      1381        3755              transience
22840      1948        8181           swimming pool
41694      1948        8181           swimming pool
23030      4771      325818              frightened
41683      4771      325818              frightened
12348      7446      167477               land mine
41700      7446      167477               land mine
23273     10483         378                  prison
41697     10483         378                  prison
35357     24420         818  based on novel or book
41682     24420         818  based on novel or book
465       49026        1437                 burglar
41693     49026        1437                 burglar
15135     49529        3801            space travel
41687     49529        3801            space travel
10709     75780      226425           mass shooting
41685     75780      226425           mass shooting
41164     77866      317226  owe money to criminals
41689     77866      317226  owe money to criminals
31772    158011       14688      multiple stabbings
41686    158011       14688      multiple stabbings
5795     206647      325763               ambiguous
41695    206647      325763               ambiguous
35310    321741         579       american football
41691    321741         579       american football
34352    339397       10048         unrequited love
41699    339397       10048         unrequited love
19079    631843      181324          existentialism
41688    631843      181324          existentialism

In [58]:
movies_keyword_clean.duplicated(
    subset=['movie_id', 'keyword_id']
).sum()

np.int64(20)

In [59]:
orphan_movies_keyword = movies_keyword_clean[
    ~movies_keyword_clean['movie_id'].isin(
        movies_clean['movie_id']
    )
]

print(
    "Orphan movie relationships:",
    len(orphan_movies_keyword)
)

Orphan movie relationships: 0

In [60]:
print(
    "Invalid movie IDs:",
    (movies_keyword_clean['movie_id'] <= 0).sum()
)

print(
    "Invalid keyword IDs:",
    (movies_keyword_clean['keyword_id'] <= 0).sum()
)

Invalid movie IDs: 0
Invalid keyword IDs: 0

In [61]:
print(
    "Empty keyword names:",
    (movies_keyword_clean['keyword_name'].str.strip() == '').sum()
)

Empty keyword names: 0

In [62]:
placeholders = [
    'Unknown',
    'unknown',
    'N/A',
    'NA',
    'NULL',
    'null'
]

movies_keyword_clean[
    movies_keyword_clean['keyword_name'].isin(placeholders)
]

Empty DataFrame
Columns: [movie_id, keyword_id, keyword_name]
Index: []

In [63]:
movies_keyword_clean['keyword_name'] = (
    movies_keyword_clean['keyword_name'].str.strip()
)

In [64]:
keyword_name_counts = (
    movies_keyword_clean
    .groupby('keyword_id')['keyword_name']
    .nunique()
)

keyword_name_counts[
    keyword_name_counts > 1
]

Series([], Name: keyword_name, dtype: int64)

In [65]:
movies_keyword_clean = movies_keyword_clean.drop_duplicates(
    subset=['movie_id', 'keyword_id']
)

In [66]:
movies_keyword_clean = movies_keyword_clean.reset_index(drop=True)

In [67]:
print("Exact duplicates:",
      movies_keyword_clean.duplicated().sum())

print("Duplicate movie-keyword relationships:",
      movies_keyword_clean.duplicated(
          subset=['movie_id', 'keyword_id']
      ).sum())

print("Orphan movie relationships:",
      len(orphan_movies_keyword))

print("Invalid movie IDs:",
      (movies_keyword_clean['movie_id'] <= 0).sum())

print("Invalid keyword IDs:",
      (movies_keyword_clean['keyword_id'] <= 0).sum())

print("Empty keyword names:",
      (movies_keyword_clean['keyword_name'].str.strip() == '').sum())

print("Keyword IDs with multiple names:",
      (keyword_name_counts > 1).sum())

Exact duplicates: 0
Duplicate movie-keyword relationships: 0
Orphan movie relationships: 0
Invalid movie IDs: 0
Invalid keyword IDs: 0
Empty keyword names: 0
Keyword IDs with multiple names: 0

In [68]:
movies_keyword_clean.to_csv(
    'movies_keyword_clean.csv',
    index=False
)

In [69]:
df = pd.read_csv('cast.csv')

In [70]:
df.columns

Index(['cast_row_id', 'movie_id', 'person_id', 'actor_name', 'character_name',
       'cast_order'],
      dtype='str')

In [71]:
df.shape

(24917, 6)

In [72]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24917 entries, 0 to 24916
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cast_row_id     24917 non-null  int64
 1   movie_id        24917 non-null  int64
 2   person_id       24917 non-null  int64
 3   actor_name      24917 non-null  str
 4   character_name  24906 non-null  str
 5   cast_order      24917 non-null  int64
dtypes: int64(4), str(2)
memory usage: 1.7 MB

In [73]:
cast_clean = df.copy()

In [74]:
cast_clean.isnull().sum()

cast_row_id        0
movie_id           0
person_id          0
actor_name         0
character_name    11
cast_order         0
dtype: int64

In [75]:
cast_clean[
    cast_clean['character_name'].isnull()
]

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
14465,14466,97370,1245,Scarlett Johansson,NaN,0
14466,14467,97370,1047644,Jeremy McWilliams,NaN,1
14467,14468,97370,1711557,Lynsey Taylor Mackay,NaN,2
14468,14469,97370,1711559,Dougie McConnell,NaN,3
14469,14470,97370,1711561,Kevin McAlinden,NaN,4
14470,14471,97370,1711616,D. Meade,NaN,5
14471,14472,97370,74841,Andrew Gorman,NaN,6
14472,14473,97370,1711626,Joe Szula,NaN,7
14473,14474,97370,136796,Kryštof Hádek,NaN,8
14474,14475,97370,1711628,Roy Armstrong,NaN,9
20870,20871,5156,1077250,Emma Druetti,NaN,9

In [76]:
cast_clean.duplicated().sum()

np.int64(15)

In [77]:
cast_clean[
    cast_clean.duplicated(keep=False)
].sort_values(['movie_id', 'cast_order'])

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
516,517,105,1067,Marc McClure,Dave McFly,6
24916,517,105,1067,Marc McClure,Dave McFly,6
1336,1337,1422,6193,Leonardo DiCaprio,Billy,0
24907,1337,1422,6193,Leonardo DiCaprio,Billy,0
8019,8020,1584,70851,Jack Black,Dewey Finn,0
24911,8020,1584,70851,Jack Black,Dewey Finn,0
5598,5599,1734,18918,Dwayne Johnson,Mathayus / The Scorpion King,7
24904,5599,1734,18918,Dwayne Johnson,Mathayus / The Scorpion King,7
12826,12827,1948,39391,Edi Gathegi,Haitian Cabbie,7
24914,12827,1948,39391,Edi Gathegi,Haitian Cabbie,7
4534,4535,8392,55664,Chika Sakamoto,Mei Kusakabe (voice),1
24903,4535,8392,55664,Chika Sakamoto,Mei Kusakabe (voice),1
17361,17362,10494,84509,Yosuke Akimoto,Tejima (voice),6
24915,17362,10494,84509,Yosuke Akimoto,Tejima (voice),6
23503,23504,49526,24045,Joseph Gordon-Levitt,Wilee,0
24905,23504,49526,24045,Joseph Gordon-Levitt,Wilee,0
17698,17699,58224,9048,Clark Gregg,Nat Jones,5
24912,17699,58224,9048,Clark Gregg,Nat Jones,5
20627,20628,239571,61011,Clarke Peters,Morgan Dupree,6
24913,20628,239571,61011,Clarke Peters,Morgan Dupree,6
3296,3297,337339,17647,Michelle Rodriguez,Letty Ortiz,3
24910,3297,337339,17647,Michelle Rodriguez,Letty Ortiz,3
21337,21338,407436,1007683,Jack Reynor,Brother Wolf (voice),7
24906,21338,407436,1007683,Jack Reynor,Brother Wolf (voice),7
17316,17317,415842,2232,Michael Keaton,Stan Hurley,1
24908,17317,415842,2232,Michael Keaton,Stan Hurley,1
9423,9424,479455,7056,Emma Thompson,Agent O,5
24902,9424,479455,7056,Emma Thompson,Agent O,5
20438,20439,1100988,6970,Christopher Fulford,Sam,7
24909,20439,1100988,6970,Christopher Fulford,Sam,7

In [78]:
cast_clean['cast_row_id'].duplicated().sum()

np.int64(15)

In [79]:
print(
    "Invalid cast_row_id:",
    (cast_clean['cast_row_id'] <= 0).sum()
)

print(
    "Invalid movie_id:",
    (cast_clean['movie_id'] <= 0).sum()
)

print(
    "Invalid person_id:",
    (cast_clean['person_id'] <= 0).sum()
)

Invalid cast_row_id: 0
Invalid movie_id: 0
Invalid person_id: 0

In [80]:
orphan_cast_movies = cast_clean[
    ~cast_clean['movie_id'].isin(
        movies_clean['movie_id']
    )
]

print(
    "Orphan movie relationships:",
    len(orphan_cast_movies)
)

Orphan movie relationships: 0

In [81]:
print(
    "Empty actor names:",
    (cast_clean['actor_name'].str.strip() == '').sum()
)

Empty actor names: 0

In [82]:
print(
    "Empty character names:",
    (cast_clean['character_name'].fillna('').str.strip() == '').sum()
)

Empty character names: 11

In [83]:
cast_clean[
    cast_clean['character_name'].isin(
        ['Unknown', 'unknown', 'N/A', 'NA', 'NULL', 'null']
    )
]

Empty DataFrame
Columns: [cast_row_id, movie_id, person_id, actor_name, character_name, cast_order]
Index: []

In [84]:
print(
    "Negative cast_order:",
    (cast_clean['cast_order'] < 0).sum()
)

Negative cast_order: 0

In [85]:
cast_clean['cast_order'].describe()

count    24917.000000
mean         4.489666
std          2.870028
min          0.000000
25%          2.000000
50%          4.000000
75%          7.000000
max          9.000000
Name: cast_order, dtype: float64

In [86]:
cast_clean['cast_order'].value_counts().sort_index().head(20)

cast_order
0    2501
1    2500
2    2498
3    2498
4    2496
5    2496
6    2494
7    2488
8    2479
9    2467
Name: count, dtype: int64

In [87]:
cast_clean.duplicated(
    subset=['movie_id', 'person_id']
).sum()

np.int64(15)

In [88]:
cast_clean[
    cast_clean.duplicated(
        subset=['movie_id', 'person_id'],
        keep=False
    )
].sort_values(['movie_id', 'person_id'])

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
516,517,105,1067,Marc McClure,Dave McFly,6
24916,517,105,1067,Marc McClure,Dave McFly,6
1336,1337,1422,6193,Leonardo DiCaprio,Billy,0
24907,1337,1422,6193,Leonardo DiCaprio,Billy,0
8019,8020,1584,70851,Jack Black,Dewey Finn,0
24911,8020,1584,70851,Jack Black,Dewey Finn,0
5598,5599,1734,18918,Dwayne Johnson,Mathayus / The Scorpion King,7
24904,5599,1734,18918,Dwayne Johnson,Mathayus / The Scorpion King,7
12826,12827,1948,39391,Edi Gathegi,Haitian Cabbie,7
24914,12827,1948,39391,Edi Gathegi,Haitian Cabbie,7
4534,4535,8392,55664,Chika Sakamoto,Mei Kusakabe (voice),1
24903,4535,8392,55664,Chika Sakamoto,Mei Kusakabe (voice),1
17361,17362,10494,84509,Yosuke Akimoto,Tejima (voice),6
24915,17362,10494,84509,Yosuke Akimoto,Tejima (voice),6
23503,23504,49526,24045,Joseph Gordon-Levitt,Wilee,0
24905,23504,49526,24045,Joseph Gordon-Levitt,Wilee,0
17698,17699,58224,9048,Clark Gregg,Nat Jones,5
24912,17699,58224,9048,Clark Gregg,Nat Jones,5
20627,20628,239571,61011,Clarke Peters,Morgan Dupree,6
24913,20628,239571,61011,Clarke Peters,Morgan Dupree,6
3296,3297,337339,17647,Michelle Rodriguez,Letty Ortiz,3
24910,3297,337339,17647,Michelle Rodriguez,Letty Ortiz,3
21337,21338,407436,1007683,Jack Reynor,Brother Wolf (voice),7
24906,21338,407436,1007683,Jack Reynor,Brother Wolf (voice),7
17316,17317,415842,2232,Michael Keaton,Stan Hurley,1
24908,17317,415842,2232,Michael Keaton,Stan Hurley,1
9423,9424,479455,7056,Emma Thompson,Agent O,5
24902,9424,479455,7056,Emma Thompson,Agent O,5
20438,20439,1100988,6970,Christopher Fulford,Sam,7
24909,20439,1100988,6970,Christopher Fulford,Sam,7

In [89]:
print("Exact duplicates:",
      cast_clean.duplicated().sum())

print("Duplicate cast_row_id:",
      cast_clean['cast_row_id'].duplicated().sum())

print("Duplicate movie-person:",
      cast_clean.duplicated(
          subset=['movie_id', 'person_id']
      ).sum())

print("Orphan movies:",
      len(orphan_cast_movies))

print("Invalid cast_row_id:",
      (cast_clean['cast_row_id'] <= 0).sum())

print("Invalid movie_id:",
      (cast_clean['movie_id'] <= 0).sum())

print("Invalid person_id:",
      (cast_clean['person_id'] <= 0).sum())

print("Empty actor names:",
      (cast_clean['actor_name'].str.strip() == '').sum())

print("Missing character names:",
      cast_clean['character_name'].isnull().sum())

print("Negative cast_order:",
      (cast_clean['cast_order'] < 0).sum())

Exact duplicates: 15
Duplicate cast_row_id: 15
Duplicate movie-person: 15
Orphan movies: 0
Invalid cast_row_id: 0
Invalid movie_id: 0
Invalid person_id: 0
Empty actor names: 0
Missing character names: 11
Negative cast_order: 0

In [90]:
cast_clean = cast_clean.drop_duplicates()

In [91]:
cast_clean = cast_clean.reset_index(drop=True)

In [92]:
print("Shape:", cast_clean.shape)
print("Exact duplicates:", cast_clean.duplicated().sum())

Shape: (24902, 6)
Exact duplicates: 0

In [93]:
cast_clean['character_name'] = (
    cast_clean['character_name'].fillna('Unknown')
)

In [94]:
cast_clean['cast_order'].describe()

count    24902.000000
mean         4.489920
std          2.870055
min          0.000000
25%          2.000000
50%          4.000000
75%          7.000000
max          9.000000
Name: cast_order, dtype: float64

In [95]:
print("Zero cast_order:",
      (cast_clean['cast_order'] == 0).sum())

Zero cast_order: 2498

In [96]:
print("Shape:", cast_clean.shape)

print("\nMissing values:")
print(cast_clean.isnull().sum())

print("\nExact duplicates:")
print(cast_clean.duplicated().sum())

print("\nDuplicate cast_row_id:")
print(cast_clean['cast_row_id'].duplicated().sum())

print("\nDuplicate movie-person:")
print(
    cast_clean.duplicated(
        subset=['movie_id', 'person_id']
    ).sum()
)

print("\nOrphan movies:")
print(
    (~cast_clean['movie_id'].isin(
        movies_clean['movie_id']
    )).sum()
)

print("\nInvalid cast_row_id:")
print((cast_clean['cast_row_id'] <= 0).sum())

print("\nInvalid movie_id:")
print((cast_clean['movie_id'] <= 0).sum())

print("\nInvalid person_id:")
print((cast_clean['person_id'] <= 0).sum())

print("\nEmpty actor names:")
print((cast_clean['actor_name'].str.strip() == '').sum())

print("\nNegative cast_order:")
print((cast_clean['cast_order'] < 0).sum())

Shape: (24902, 6)

Missing values:
cast_row_id       0
movie_id          0
person_id         0
actor_name        0
character_name    0
cast_order        0
dtype: int64

Exact duplicates:
0

Duplicate cast_row_id:
0

Duplicate movie-person:
0

Orphan movies:
0

Invalid cast_row_id:
0

Invalid movie_id:
0

Invalid person_id:
0

Empty actor names:
0

Negative cast_order:
0

In [97]:
cast_clean['character_name'].value_counts().head(20)

character_name
David         25
Jack          24
Tom           23
Sam           21
Frank         21
James Bond    21
M             21
Paul          21
Sarah         20
Mother        20
Max           20
Charlie       19
Peter         18
Joe           18
Martin        18
Alice         18
Carl          17
Mary          17
Mike          17
Father        17
Name: count, dtype: int64

In [98]:
cast_clean[
    cast_clean['character_name'].isin(['Unknown', 'unknown', 'N/A', 'NA'])
]

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
14465,14466,97370,1245,Scarlett Johansson,Unknown,0
14466,14467,97370,1047644,Jeremy McWilliams,Unknown,1
14467,14468,97370,1711557,Lynsey Taylor Mackay,Unknown,2
14468,14469,97370,1711559,Dougie McConnell,Unknown,3
14469,14470,97370,1711561,Kevin McAlinden,Unknown,4
14470,14471,97370,1711616,D. Meade,Unknown,5
14471,14472,97370,74841,Andrew Gorman,Unknown,6
14472,14473,97370,1711626,Joe Szula,Unknown,7
14473,14474,97370,136796,Kryštof Hádek,Unknown,8
14474,14475,97370,1711628,Roy Armstrong,Unknown,9
20870,20871,5156,1077250,Emma Druetti,Unknown,9

In [99]:
cast_clean['character_name'] = (
    cast_clean['character_name']
    .str.replace(r'\s*\([^)]*\)', '', regex=True)
    .str.strip()
)

In [100]:
cast_clean.to_csv('cast_clean.csv', index=False)

In [101]:
df = pd.read_csv('crew.csv')

In [102]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7297 entries, 0 to 7296
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   crew_row_id  7297 non-null   int64
 1   movie_id     7297 non-null   int64
 2   person_id    7297 non-null   int64
 3   person_name  7297 non-null   str
 4   job          7297 non-null   str
 5   department   7297 non-null   str
dtypes: int64(3), str(3)
memory usage: 552.0 KB

In [103]:
crew_clean = df.copy()

In [104]:
print(
    "Exact duplicates:",
    crew_clean.duplicated().sum()
)

Exact duplicates: 8

In [105]:
print(
    "Duplicate crew_row_id:",
    crew_clean['crew_row_id'].duplicated().sum()
)

Duplicate crew_row_id: 8

In [106]:
print(
    "Invalid crew_row_id:",
    (crew_clean['crew_row_id'] <= 0).sum()
)

Invalid crew_row_id: 0

In [107]:
print(
    "Duplicate movie-person-job:",
    crew_clean.duplicated(
        subset=['movie_id', 'person_id', 'job']
    ).sum()
)

Duplicate movie-person-job: 8

In [108]:
orphan_crew_movies = crew_clean[
    ~crew_clean['movie_id'].isin(
        movies_clean['movie_id']
    )
]

print(
    "Orphan movie relationships:",
    len(orphan_crew_movies)
)

Orphan movie relationships: 0

In [109]:
print(
    "Invalid movie_id:",
    (crew_clean['movie_id'] <= 0).sum()
)

print(
    "Invalid person_id:",
    (crew_clean['person_id'] <= 0).sum()
)

Invalid movie_id: 0
Invalid person_id: 0

In [110]:
print(
    "Empty person_name:",
    (crew_clean['person_name'].str.strip() == '').sum()
)

Empty person_name: 0

In [111]:
print(
    "Empty job:",
    (crew_clean['job'].str.strip() == '').sum()
)

Empty job: 0

In [112]:
print(
    "Empty department:",
    (crew_clean['department'].str.strip() == '').sum()
)

Empty department: 0

In [113]:
crew_clean[
    crew_clean['job'].isin(
        ['Unknown', 'unknown', 'N/A', 'NA', 'NULL', 'null']
    )
]

Empty DataFrame
Columns: [crew_row_id, movie_id, person_id, person_name, job, department]
Index: []

In [114]:
crew_clean[
    crew_clean['department'].isin(
        ['Unknown', 'unknown', 'N/A', 'NA', 'NULL', 'null']
    )
]

Empty DataFrame
Columns: [crew_row_id, movie_id, person_id, person_name, job, department]
Index: []

In [115]:
print("Shape:", crew_clean.shape)

print("\nMissing values:")
print(crew_clean.isnull().sum())

print(
    "\nExact duplicates:",
    crew_clean.duplicated().sum()
)

print(
    "Duplicate crew_row_id:",
    crew_clean['crew_row_id'].duplicated().sum()
)

print(
    "Duplicate movie-person-job:",
    crew_clean.duplicated(
        subset=['movie_id', 'person_id', 'job']
    ).sum()
)

print(
    "Orphan movies:",
    len(orphan_crew_movies)
)

print(
    "Invalid crew_row_id:",
    (crew_clean['crew_row_id'] <= 0).sum()
)

print(
    "Invalid movie_id:",
    (crew_clean['movie_id'] <= 0).sum()
)

print(
    "Invalid person_id:",
    (crew_clean['person_id'] <= 0).sum()
)

print(
    "Empty person_name:",
    (crew_clean['person_name'].str.strip() == '').sum()
)

print(
    "Empty job:",
    (crew_clean['job'].str.strip() == '').sum()
)

print(
    "Empty department:",
    (crew_clean['department'].str.strip() == '').sum()
)

Shape: (7297, 6)

Missing values:
crew_row_id    0
movie_id       0
person_id      0
person_name    0
job            0
department     0
dtype: int64

Exact duplicates: 8
Duplicate crew_row_id: 8
Duplicate movie-person-job: 8
Orphan movies: 0
Invalid crew_row_id: 0
Invalid movie_id: 0
Invalid person_id: 0
Empty person_name: 0
Empty job: 0
Empty department: 0

In [116]:
crew_clean = crew_clean.drop_duplicates()

In [117]:
crew_clean = crew_clean.reset_index(drop=True)

In [118]:
print("Shape:", crew_clean.shape)

print("\nMissing values:")
print(crew_clean.isnull().sum())

print("\nExact duplicates:")
print(crew_clean.duplicated().sum())

print("\nDuplicate crew_row_id:")
print(crew_clean['crew_row_id'].duplicated().sum())

print("\nDuplicate movie-person-job:")
print(
    crew_clean.duplicated(
        subset=['movie_id', 'person_id', 'job']
    ).sum()
)

print("\nOrphan movies:")
print(
    (~crew_clean['movie_id'].isin(
        movies_clean['movie_id']
    )).sum()
)

print("\nInvalid crew_row_id:")
print((crew_clean['crew_row_id'] <= 0).sum())

print("\nInvalid movie_id:")
print((crew_clean['movie_id'] <= 0).sum())

print("\nInvalid person_id:")
print((crew_clean['person_id'] <= 0).sum())

print("\nEmpty person names:")
print((crew_clean['person_name'].str.strip() == '').sum())

print("\nEmpty jobs:")
print((crew_clean['job'].str.strip() == '').sum())

print("\nEmpty departments:")
print((crew_clean['department'].str.strip() == '').sum())

Shape: (7289, 6)

Missing values:
crew_row_id    0
movie_id       0
person_id      0
person_name    0
job            0
department     0
dtype: int64

Exact duplicates:
0

Duplicate crew_row_id:
0

Duplicate movie-person-job:
0

Orphan movies:
0

Invalid crew_row_id:
0

Invalid movie_id:
0

Invalid person_id:
0

Empty person names:
0

Empty jobs:
0

Empty departments:
0

In [119]:
crew_clean.to_csv(
    'crew_clean.csv',
    index=False
)